name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t formation-app .

      - name: Run container
        run: docker run -d -p 5000:5000 --name app formation-app

      - name: Check container status
        run: |
          sleep 3
          docker ps
          docker logs app

      - name: Wait and test
        run: |
          sleep 10
          curl -v http://localhost:5000/

      - name: Cleanup
        if: always()
        run: |
          docker stop app || true
          docker rm app || true
